# Generated by Django 5.2.3 on 2025-08-25 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0011_site_site_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255, verbose_name='المقال')),
                ('article_details', models.TextField(verbose_name='تفاصيل المقال')),
                ('article_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط المقال')),
                ('publish_date', models.DateField(verbose_name='تاريخ النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('status', models.CharField(choices=[('in_progress', '⏳ جاري العمل'), ('upload', 'تم الرفع'), ('publish', 'تم النشر'), ('done', '✅ مكتملة')], default='in_progress', max_length=20, verbose_name='حالة المهمة')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='الصورة المطلوبة من المصمم')),
                ('image_type', models.CharField(blank=True, choices=[('in_progress', '⏳ جاري العمل'), ('send', 'تم الارسال للكاتب'), ('publish', 'تم النشر')], default='in_progress', max_length=20, null=True, verbose_name='حالة الصور')),
                ('image_details', models.TextField(blank=True, null=True, verbose_name='تفاصيل الصور')),
                ('article_type_W_R_A_B', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.article_type_w_r_a_b', verbose_name=' نوع المقال( تحذير / تقييم/تعليمي/افضل شركات)')),
                ('publish_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.site', verbose_name='موقع النشر')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
            ],
        ),
    ]
