# Generated by Django 5.2.3 on 2025-08-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_need_image',
            field=models.CharField(blank=True, choices=[('NO', 'لا '), ('YES', 'نعم')], default='NO', max_length=20, null=True, verbose_name='هل تحتاج لصور؟'),
        ),
    ]
