# Generated by Django 5.2.3 on 2025-12-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_verification_checked',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحقق'),
        ),
        migrations.AddField(
            model_name='task',
            name='published_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='الرابط المنشور'),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_status',
            field=models.BooleanField(default=False, verbose_name='حالة التحقق'),
        ),
    ]
