# Generated by Django 5.2.3 on 2025-12-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_last_verification_checked_task_published_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='published_url',
            field=models.CharField(blank=True, max_length=7000, null=True, verbose_name='الرابط المنشور'),
        ),
    ]
