# Generated by Django 5.2.3 on 2025-08-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_need_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_status',
            field=models.CharField(blank=True, choices=[('in_progress', '⏳ جاري العمل'), ('send', 'تم الارسال للكاتب '), ('publish', '✅تم الرفع على الموقع')], default='in_progress', max_length=20, null=True, verbose_name='حالة الصورر'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image_type',
            field=models.CharField(blank=True, choices=[('Featured image', 'صورة بارزة'), ('Interior photo', 'صورة داخلية')], default='Featured image', max_length=20, null=True, verbose_name='حالة الصور'),
        ),
    ]
