# Generated by Django 5.2.3 on 2025-09-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_image_status_alter_task_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image_type',
            field=models.CharField(blank=True, choices=[('صورة بارزة', 'صورة بارزة'), ('صورة داخلية', 'صورة داخلية')], default='صورة بارزة', max_length=20, null=True, verbose_name='نوع الصورة'),
        ),
    ]
