# Generated by Django 5.2.3 on 2025-12-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_published_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_verification_checked',
        ),
        migrations.RemoveField(
            model_name='task',
            name='verification_status',
        ),
    ]
