# Generated by Django 5.2.3 on 2025-12-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_last_verification_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='published_url',
            field=models.TextField(blank=True, max_length=7000, null=True, verbose_name='الرابط المنشور'),
        ),
    ]
