# Generated by Django 5.2.3 on 2025-12-06 12:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=ckeditor.fields.RichTextField(default=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='original_article_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط المقال الأصلي'),
        ),
    ]
