# Generated by Django 5.2.3 on 2025-12-21 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0014_contract_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('email', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان البريد الإلكتروني')),
                ('website', models.URLField(blank=True, max_length=500, null=True, verbose_name='موقع الشركة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ المدفوع')),
                ('nots', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('contract_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.contract_details', verbose_name='تفاصيل العقد')),
                ('contract_duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.contract_duration', verbose_name='مدة العقد')),
                ('site_puplished', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.site', verbose_name='الموقع المنشور عليه')),
            ],
        ),
    ]
