# Generated by Django 5.2.3 on 2025-12-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_alter_contract_duration_number_of_duration'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contract_details',
        ),
        migrations.RemoveField(
            model_name='company',
            name='site_puplished',
        ),
        migrations.AddField(
            model_name='company',
            name='contract_details',
            field=models.ManyToManyField(blank=True, to='categories.contract_details', verbose_name='تفاصيل العقد'),
        ),
        migrations.AddField(
            model_name='company',
            name='site_puplished',
            field=models.ManyToManyField(blank=True, to='categories.site', verbose_name='الموقع المنشور عليه'),
        ),
    ]
